version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
      - ..:/workspace
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50076:50075"
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode-1:50075 datanode-2:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0

  presto-coordinator:
    build: ./prestodb_docker
    command: --is_coordinator=true --node_id=56283df2-3b7e-11eb-b7a8-7b26edbbee40 --discovery_uri http://presto-coordinator:8080
    ports:
      - "8080:8080"

  presto-worker-1:
    build: ./prestodb_docker
    command: --is_coordinator=false --node_id=56283df2-3b7e-11eb-b7a8-7b26edbbee41 --discovery_uri http://presto-coordinator:8080
    ports:
      - "8081:8080"

  presto-worker-2:
    build: ./prestodb_docker
    command: --is_coordinator=false --node_id=56283df2-3b7e-11eb-b7a8-7b26edbbee42 --discovery_uri http://presto-coordinator:8080
    ports:
      - "8082:8080"

#  presto-worker-3:
#    build: ./prestodb_docker
#    command: --is_coordinator=false --node_id=presto-worker-3 --discovery_uri http://presto-coordinator:8080
#    ports:
#      - "8083:8080"

volumes:
  namenode:
  datanode1:
  datanode2:
